/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Elin (https://sketchfab.com/ElinHohler)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tropical-island-f91862f8c38b481aa19edccac851eefb
Title: Tropical Island
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber"
import { a } from '@react-spring/three'
import tropical_island from '../assets/3d/tropical_island.glb'

export function Island(props) {
    const islandRef = useRef();
  const { nodes, materials } = useGLTF(tropical_island);
  return (
    <a.group ref={islandRef} {...props}>
        <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={materials.Cat_Palm}
        />
        <mesh
            name="Object_6"
            geometry={nodes.Object_6.geometry}
            material={materials.Areca_Palm}
        />
        <mesh
            name="Object_8"
            geometry={nodes.Object_8.geometry}
            material={materials.Areca_Palm}
        />
        <mesh
            name="Object_10"
            geometry={nodes.Object_10.geometry}
            material={materials.Cat_Palm}
        />
        <mesh
            name="Object_12"
            geometry={nodes.Object_12.geometry}
            material={materials.Tropical_Palm}
        />
        <mesh
            name="Object_14"
            geometry={nodes.Object_14.geometry}
            material={materials.Areca_Palm}
        />
        <mesh
            name="Object_16"
            geometry={nodes.Object_16.geometry}
            material={materials.Areca_Palm}
        />
        <mesh
            name="Object_18"
            geometry={nodes.Object_18.geometry}
            material={materials.Areca_Palm}
        />
        <mesh
            name="Object_20"
            geometry={nodes.Object_20.geometry}
            material={materials.Tropical_Palm}
        />
        <mesh
            name="Object_22"
            geometry={nodes.Object_22.geometry}
            material={materials.Tropical_Palm}
        />
        <mesh
            name="Object_24"
            geometry={nodes.Object_24.geometry}
            material={materials.Cat_Palm}
        />
        <mesh
            name="Object_26"
            geometry={nodes.Object_26.geometry}
            material={materials.Cat_Palm}
        />
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
            name="Object_31"
            geometry={nodes.Object_31.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Object_31.skeleton}
            />
        <mesh
            name="Object_60"
            geometry={nodes.Object_60.geometry}
            material={materials.Treibholz}
        />
        <mesh
            name="Object_64"
            geometry={nodes.Object_64.geometry}
            material={materials.RocksBig}
        />
        <mesh
            name="Object_66"
            geometry={nodes.Object_66.geometry}
            material={materials.BeachBaked}
        />
        <mesh
            name="Object_68"
            geometry={nodes.Object_68.geometry}
            material={materials.Palme}
        />
        <mesh
            name="Object_70"
            geometry={nodes.Object_70.geometry}
            material={materials.Palme_Blaetter}
        />
        <mesh
            name="Object_72"
            geometry={nodes.Object_72.geometry}
            material={materials.RocksSmall}
        />
        <mesh
            name="Object_74"
            geometry={nodes.Object_74.geometry}
            material={materials["Skybox.001"]}
        />
    </a.group>
                
  );
}

export default Island;